### ISSUE TITLE
irccUrl in README-SCALAR.md

### ISSUE THREAD

**Issue by kennetn** [tmrobert8/openhab2-addons#5]
On the help page for Scalar Thing Configuration there is a irccUrl.
Should this not be on the IRCC page ?

**Comment by tmrobert8** [comment]
There is an irccUrl for scalar.  Scalar itself doesn't implement an IRCC channel but any scalar implementation usually has an IRCC service active as well.   Since an IRCC command is popular and generally the IRCC service exists - I've 'fudged' the scalar service to look like it supports IRCC (but simply delegates to the IRCC service) and thus I need the IRCC URL (url to the IRCC service) as part of the configuration for scalar.
